# Generated by Django 4.2.4 on 2023-08-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id", # 唯一的id用来表示数据库中的数据，django自动创建
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),# 下面是你定义的属性
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("stock", models.IntegerField()),
                ("iamge_url", models.CharField(max_length=2083)),
            ],
        ),
    ]
