# Generated by Django 4.2.4 on 2023-08-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_offer_code_alter_offer_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="iamge_url",
            new_name="image_url",
        ),
    ]
